apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  params:
    - name: script
      type: string
      description: The script to run
      default: |
        echo "No cleanup script provided."
  steps:
    - name: cleanup
      image: "ubuntu"
      script: |
        #!/bin/bash
        $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  params:
    - name: args
      type: array
      description: The arguments to pass to the nose command
      default:
        - "-v"
        - "--with-spec"
        - "--spec-color"
        - "--with-coverage"
        - "--cover-package=service"
  steps:
    - name: test
      image: "python:3.9-slim"
      script: |
        #!/bin/bash
        pip install -r requirements.txt
        nosetests $(params.args)
